### ISSUE TITLE
How to disable dates, highlight multiple dates, and show holidays?

### ISSUE THREAD

**Issue by jimmy818** [wojtekmaj/react-calendar#152] opened 2018-11-15 06:05 UTC
I am working on ReactJS project. I want to use Calendar which will highlight Indonesian holidays, and also I want to highlight some specific dates and disable other dates.

I am searching over the google but didn't get any solution regarding it.

I would love to appreciate any help from you guys.

Thanks in advance.

**Comment by wojtekmaj** [comment] 2018-11-15 09:57
Duplicate of #30 
Duplicate of #79 

Please look at these issues to find your answers.

**Closed by wojtekmaj** 2018-11-15 09:57 UTC
