### ISSUE TITLE
MultidateSelect & rangeSelectionofDays

### ISSUE THREAD

**Issue by ronit65** [wojtekmaj/react-calendar#155] opened 2018-12-06 04:56 UTC
Hi,
I want to have the events inside the calendar so that when I click Ctrl+ Mouse click I should be able to select multiple dates and same for range selection of days using Shift + Mouse Click

**Comment by wojtekmaj** [comment] 2018-12-24 10:32
Duplicate of #136

**Closed by wojtekmaj** 2018-12-24 10:32 UTC
