### ISSUE TITLE
Selection multiple dates instead of range

### ISSUE THREAD

**Issue by Aliaksandr-Yanushkevich** [wojtekmaj/react-calendar#441] opened 2020-09-30 14:46 UTC
Hello everyone. I use react-calendar in my project. I need to select several different days, but I can't do it. Is there possibility to do it?  I've found only range of dates selection in documentation.

This question asked [here](https://stackoverflow.com/questions/56952474/display-multiple-dates-on-react-calendar), but nobody answered it.

**Comment by wojtekmaj** [comment] 2020-10-09 09:47
Duplicate of https://github.com/wojtekmaj/react-calendar/issues/136

See also:

https://github.com/wojtekmaj/react-calendar/issues/372#issuecomment-626765879

https://github.com/wojtekmaj/react-calendar/issues/295#issuecomment-576028778

**Closed by wojtekmaj** 2020-10-09 09:47 UTC
Labels: duplicate, enhancement
