### ISSUE TITLE
Feature request: Having the ability to select multiple dates 

### ISSUE THREAD

**Issue by lucasriondel** [wojtekmaj/react-calendar#892] opened 2023-08-22 09:22 UTC
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

I'd like a feature that allow the user to select multiple dates, instead of using ranges. I'm trying to implement an appointment planner and this doesn't seem possible as of now, but shouldn't be too hard to implement giving the solid codebase. 

What do you think ?

### Proposed solution

add an `allowMultipleDaySelection: boolean` prop, default to false, that will trigger this behavior.
`value` and `onChange` will then allow a `Date[]` in addition to `Date | [Date, Date}`

**Comment by wojtekmaj** [comment] 2023-09-25 08:04
Duplicate of #136

**Closed by wojtekmaj** 2023-09-25 08:04 UTC
Labels: enhancement
