### ISSUE TITLE
Add possibility to change button as wrapper

### ISSUE THREAD

**Issue by ericlifs** [wojtekmaj/react-calendar#164] opened 2019-01-18 20:37 UTC
I have a component (inside the `<button>` that react-calendar provides as the wrapper for each tile) that has a hover event. On Chrome the hover event of the children is getting fired but on Firefox it does not work as it says here https://bugzilla.mozilla.org/show_bug.cgi?id=843003

So I wanted to know if it's possible to give the developer the possibility to change the wrapper for each tile (for example to a `<div>`) in order to make the hover event triggerable in all browsers.

Thanks!

**Comment by wojtekmaj** [comment] 2019-02-08 08:22
Duplicate of #85 - can reopen if necessary

**Closed by wojtekmaj** 2019-02-08 08:22 UTC
Labels: duplicate, enhancement, question
