### ISSUE TITLE
weekNumber '11' glitches

### ISSUE THREAD

**Issue by amansur** [wojtekmaj/react-calendar#17] opened 2017-12-12 21:59 UTC
Hi wojtekmaj

I noticed an issue with the weekNumbers. If you navigate to March 2015, "11" appears twice. If you navigate forward or backward by a month, a duplicate "11" gets pinned for each time you do that.

The same thing happens on March 2009.

Thanks for looking into it!

**Comment by wojtekmaj** [comment] 2017-12-12 22:18
Hey @amansur,
would you please tell me on what browser are you testing this? I'm could not reproduce this issue, I tested on Firefox 57, Chrome 63 and Microsoft Edge 16.17046 🤔

**Comment by amansur** [comment] 2017-12-13 01:50
I'm seeing this issue on the following

Win10 - Firefox 57, Chrome 63, Edge 41.16299.15.0
MacOS Sierra - Firefox 57, Chrome 63

![react-calendar-glitch-2](https://user-images.githubusercontent.com/8364162/33917492-9b58f68e-df7c-11e7-8158-26116d26b74b.jpg)
![react-calendar-glitch-1](https://user-images.githubusercontent.com/8364162/33917491-9b4acfaa-df7c-11e7-870a-96c7b4a7fc19.jpg)

**Comment by wojtekmaj** [comment] 2017-12-15 07:33
Thanks so much and sorry for the delay. I'll have a look on this today.

**Comment by wojtekmaj** [comment] 2017-12-15 18:47
Hey,
I was again trying my best to reproduce but by no means I was able to do this. I updated the sample page to the newest version though; perhaps the issue you were running to was fixed some time ago? Looks to me like something screwed up in React itself.

**Comment by wojtekmaj** [comment] 2017-12-16 18:25
Thanks again! I'll have a fix in incoming release.

**Comment by wojtekmaj** [comment] 2017-12-16 19:33
Fixed in 2.8.0.

**Closed by wojtekmaj** 2017-12-16 19:33 UTC
Labels: bug

**Comment by amansur** [comment] 2017-12-18 18:02
Thank you very much! Confirming the bug is gone in 2.8.0.
