### ISSUE TITLE
Showing two month at a time and month and year range selction

### ISSUE THREAD

**Issue by LahiruRajapaksha** [wojtekmaj/react-calendar#170] opened 2019-02-04 08:33 UTC
Hi,
There is no option to add two month at a time like #82 and selecting month and year ranges. Will you gonna improve it?

**Comment by wojtekmaj** [comment] 2019-02-13 18:41
Yes, there are plans to do it. I can't give you any dates at the moment, though.

Duplicate of #82

**Comment by wojtekmaj** [comment] 2019-02-13 18:42
Duplicate of #82

**Closed by wojtekmaj** 2019-02-13 18:41 UTC
Labels: enhancement, question

**Comment by LahiruRajapaksha** [comment] 2019-02-21 09:23
Thanks for the reply
