### ISSUE TITLE
Changing activeStartDate does not change calendar view

### ISSUE THREAD

**Issue by mantovanig** [wojtekmaj/react-calendar#43] opened 2018-03-07 09:07 UTC
Hi,

I'm trying to use the library with a custom external navigation.
So on click on next/prev of my custom navigation I update the prop "activeStartDate" but the calendar not change.

I saw that the "activeStartDate" in the state of Calendar component is not updated by props.

**Comment by wojtekmaj** [comment] 2018-03-07 21:19
Hello @mantovanig,
glad you asked. By default, the calendar displays the month in which `value` is. If no `value` is provided, then `activeStartDate` takes priority.

What do you think about this solution? Is it something you wouldn'y expect? If so, we'll think of some solution!

**Comment by mantovanig** [comment] 2018-03-08 08:35
Hello @wojtekmaj ,

I don't think I understood the approach.

Take a look this little example:
https://codesandbox.io/s/3xw8xomn8m

At start you can navigate with "prev/next" button, but if you select a day, you are no longer able to navigate because the activeStartDate prop has lost priority and I can't change the value only to navigation purpose.

I would like to get the browsing behavior of the demo:
http://projekty.wojtekmaj.pl/react-calendar/

Thanks in advance

**Comment by wojtekmaj** [comment] 2018-03-13 23:00
Hey there,
as discussed in Pull Request, I have created a [separate branch with the change](https://github.com/wojtekmaj/react-calendar/tree/change/activeStartDate-as-priority), and I will need to keep it there until version 3 - this is a change of exposed, documented behavior and as such must be considered a breaking change.

Hope you're not in a hurry with this, and if you are, for now you can get the necessary version from the [branch](https://github.com/wojtekmaj/react-calendar/tree/change/activeStartDate-as-priority) on GitHub instead of npm.

**Comment by mantovanig** [comment] 2018-03-14 10:50
Hi @wojtekmaj ,

ok perfect! 
Don't worry, for the moment, I use git url with the changes in my package json for react-calendar dependence, when you publish the 3.0 I will change it.

Thanks

**Comment by balazsorban44** [comment] 2018-04-27 17:51
@mantovanig I think I have the same problem. Could you explain how to change the `package.json` so it uses the change @wojtekmaj mentioned? Thank you

**Comment by mantovanig** [comment] 2018-04-28 08:06
Hi @balazsorban44 

This is what I've done:
- fork react-calendar
- move to branch created by @wojtekmaj 

> I have created a [separate branch with the change](https://github.com/wojtekmaj/react-calendar/tree/change/activeStartDate-as-priority)

- remove dist from .gitignore
- run build

And in my package json I put directly the commit of my fork:

`"react-calendar": "git://github.com/mantovanig/react-calendar.git#1f4f9722f39717939cd7e3910c131e2e45e1c4d0",`

If you want you can use the same.

Waiting for 3.0 💪 

Cheers

**Comment by balazsorban44** [comment] 2018-04-28 08:39
@mantovanig do you use it to pick a range, or a single value?

**Comment by wojtekmaj** [comment] 2018-05-04 10:28
That's not a bug, it's just a design approach that, if we decide to change it, has to wait for next major version to be included, if included at all.

Say you have a hotel booking page with this calendar to choose a date of your stay. You'll want the calendar to display the given value and if value is not yet given - display next month. You'd code it like so:

```js
<Calendar
  value={value} // can be null if not set
  activeStartDate={nextMonth} // fallback if value not set
/>
```

How are you supposed to do that with activeStartDate taking priority over value? That's my main concern and the reason I'm postponing this change.

**Comment by luisfuertes** [comment] 2018-05-23 09:47
When i select a range, calendar select tileDisabled days too.

And if i do a async call in onActiveDateChange function, calendar view dont update.

**Comment by mattcarpowich1** [comment] 2018-07-06 21:37
![screen shot 2018-07-06 at 2 37 04 pm](https://user-images.githubusercontent.com/27029446/42401347-17d3bfc4-812a-11e8-8679-c9b2f170d31e.png)
Here's what I did. Set the date value to today if the month is the same, otherwise let the activeStartDate take priority. Maybe this will help someone

**Comment by andyfurniss4** [comment] 2019-03-20 15:59
Seems a bit silly that once you've chosen a date, you can no longer use the navigation, no? I also have this issue and frankly it just seems crazy. If someone chooses a date and then changes their mind... then what?

**Comment by gopienkonikita** [comment] 2019-08-15 12:53
Hello @wojtekmaj ,
I use your calendar and use custom navigation panel, but i can't change the activeStartDate and 
use value same time. I like to use this calendar.  
It's screenshot with my problem:
![Calendar](https://user-images.githubusercontent.com/23257739/63095482-0c00c780-bf74-11e9-8937-e3bc89169c27.PNG)

Navigation is doesn't work... I hope you solve this problem soon.

**Comment by wojtekmaj** [comment] 2019-08-17 09:34
You're being heard. React-Calendar's current architecture doesn't allow an easy way around this, but it's on our roadmap for 3.0 - follow #216 for updates.

**Comment by wojtekmaj** [comment] 2019-09-26 12:03
Resolved in #217, scheduled for 3.0 as planned.

**Comment by wojtekmaj** [comment] 2019-09-26 12:03
Resolved in #217, scheduled for 3.0 as planned.

**Closed** 2019-09-26 12:03 UTC
Labels: enhancement

**Comment by yohanelly95** [comment] 2020-08-16 18:51
Hey @wojtekmaj, I can't set an activeStartDate currently, I am passing a value of `Thu Aug 27 2020 00:00:00 GMT+0530 (India Standard Time)` for example. And my component looks like this 
`<Calendar
                onChange={setFromDate}
                value={fromDate}
                minDate={new Date()}
                showNeighboringMonth={true}
                maxDetail="month"
                next2Label={null}
                prev2Label={null}
                activeStartDate={initialDate}
            />`

What am I doing wrong? 
So my use case is that I set values on my calendar, on redirecting I share the values using query params and rerender the component on another page using the previously set date. Any help would be great 🥇

**Comment by wojtekmaj** [comment] 2020-08-17 05:55
You shouldn't use values that are not beginning of months/years/decades/centuries (depending on the view) for activeStartDate.

**Comment by jgreen7773** [comment] 2020-09-29 22:45
> Hello @mantovanig,
> glad you asked. By default, the calendar displays the month in which `value` is. If no `value` is provided, then `activeStartDate` takes priority.
> 
> What do you think about this approach? Is it something you wouldn'y expect? If so, we'll think of some solution!

make a new attribute that does the EXACT same thing as `activeStartDate`, except don't lock calendar navigation if used in conjunction with value. I can't move months.... The only way I can find to move months is to click on the days outside of the current month displayed. If the display shows 31 as the last number, there is no possible way to go to the next month as the navigation arrows are disabled. Consider naming your new attribute as: `monthlyNavigationFollowsValue` or something....
