### ISSUE TITLE
Support for week view

### ISSUE THREAD

**Issue by Flaaj** [wojtekmaj/react-calendar#625] opened 2022-07-13 10:38 UTC
### Before you start - checklist

- [x] I have checked if this feature request is not already reported

### Description

React-calendar is hands down the nicest calendar component that i use for every use case. Except one. It misses a week view. A view with only one week from monday to sunday (or saturday to sunday for those who want).

### Proposed solution

 A view where the arrow left would decrement a week, and arrow right would increment week.
A week view would be enterable via small buttons on the left side of calendar, next to each row, a row which is a week anyway.

### Alternatives

An alternative solution is to do some hacking. I can just display: none the days I don't want and create my custom controls buuut. Would be nice to have that natively built in.

### Additional information

![image](https://user-images.githubusercontent.com/32792800/178714562-93ae1d3f-c0e5-490c-931b-cde44c727517.png)
![image](https://user-images.githubusercontent.com/32792800/178714594-5270f990-d818-45da-838b-45f5489baeb7.png)

In my early days of learning frontend development I created something like this. It's ugly but it presents the idea (sorry for polish language)

**Comment by nhockool1002** [comment] 2022-10-10 16:59
@wojtekmaj I had such a case, I just want to show 1 certain week (Monday to Sunday)
Please help me,
Thanks.

**Comment by Flaaj** [comment] 2022-10-11 16:47
@nhockool1002 I did it this way using react-calendar:
- get the number of the week you want to show
- display: none all tiles that are a different week number
- replace navigation with your own for the week view, increment/decrement a week on nav button click
- always check in which month first day of that week is so that you can show correct month

**Comment by Flaaj** [comment] 2022-10-11 17:34
@nhockool1002 I can try to write something general:

    <ReactCalendar
      activeStartDate={ ... somehow get monday of that week as a Date object and put here }
      tileContent={({ date }) => <CalendarTile date={date} />}
      tileClassName={({ date }) => {
        const isChosenWeek = dayjs(date).week() === chosenWeek && dayjs(date).year() === chosenYear;

        if (!isChosenWeek) {
          return "hidden";
        }
        
        return "";
      }}
    />

**Comment by wojtekmaj** [comment] 2023-01-11 12:20
Duplicate of #70

**Closed by wojtekmaj** 2023-01-11 12:20 UTC
Labels: enhancement
