### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by Rafi993** [wojtekmaj/react-calendar#161] opened 2018-12-30 15:48 UTC
I am getting the following error when I did yarn add and they just imported 'react-calendar'
```

vm.js:74 Uncaught SyntaxError: Unexpected token .
    at new Script (vm.js:74)
    at createScript (vm.js:246)
    at Object.runInThisContext (vm.js:298)
    at Module._compile (internal/modules/cjs/loader.js:678)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722)
    at Module.load (internal/modules/cjs/loader.js:620)
    at tryModuleLoad (internal/modules/cjs/loader.js:559)
    at Function.Module._load (internal/modules/cjs/loader.js:551)
    at Module.require (internal/modules/cjs/loader.js:658)
    at require (internal/modules/cjs/helpers.js:20)
```

**node**: v10.15.0
**os**: Debian (Linux)
**yarn**: 1.12.3
**react-calendar version**: "^2.17.5"

**Comment by Rafi993** [comment] 2018-12-30 15:48
and on a side note it would be better if you had some template for users creating issue

**Comment by wojtekmaj** [comment] 2018-12-31 08:20
Hi, thanks for reporting. This is due to a CSS file being imported (if you don't opt-out). You should configure your Webpack properly to load CSS files, or opt-out from loading the default styles by using `entry.nostyle` (more in README).

**Comment by wojtekmaj** [comment] 2018-12-31 08:20
Duplicate of #108

**Closed** 2018-12-31 08:20 UTC
Labels: duplicate, question
