### ISSUE TITLE
Broken layout in Safari mobile

### ISSUE THREAD

**Issue by lisahoong** [wojtekmaj/react-calendar#45] opened 2018-03-13 18:06 UTC
On a desktop browser this calendar appears just fine, but when I view this on my iPhone 7 in my Safari app, the last weekday's dates get pushed to the next line like this:

![image](https://user-images.githubusercontent.com/23561646/37360815-a7a7ecd2-26c7-11e8-9ad1-d2d5aed496dd.png)

**Comment by wojtekmaj** [comment] 2018-03-13 23:04
Hey Lisa,
I need a little more information to help you. Is the same issue happening when you open the following pages?

1. [Demo page](http://projects.wojtekmaj.pl/react-calendar/)
2. [Test page](http://projects.wojtekmaj.pl/react-calendar/test/)

**Comment by PiTomar** [comment] 2018-03-14 11:43
Hi,
in IE11 there is a similar issue:
![unbenannt](https://user-images.githubusercontent.com/37152440/37400446-441f5d6c-2785-11e8-9844-dc6f54044435.png)

**Comment by lisahoong** [comment] 2018-03-14 16:02
On the demo page, it looks like this:
![image](https://user-images.githubusercontent.com/23561646/37414424-73903b44-277f-11e8-8643-abf05099e544.png)

On the test page, it looks like this:
![image](https://user-images.githubusercontent.com/23561646/37414456-86f2f7e4-277f-11e8-92c2-ca9ee2a8597d.png)

Thank you for your help!

**Comment by lisahoong** [comment] 2018-03-14 16:03
![image](https://user-images.githubusercontent.com/23561646/37414534-b2a6917a-277f-11e8-9fa6-0dcf5599abf4.png)

**Comment by wojtekmaj** [comment] 2018-03-14 23:04
@lisahoong, it looks like tile elements have some additional margin or a border, which is not standard button styling. I sadly have no Safari. Would you please try using this CSS and tell me if it works for you? If it does, I'll push the fix.

```
.react-calendar__tile {
  margin: 0;
  border: 0;
}
```

@PiTomar, thanks for mentioning it - I could reproduce this, indeed IE fails to scale flex items properly.

**Comment by nathan-haines** [comment] 2018-03-15 01:36
@wojtekmaj Is that fix for IE in already? Just trying to figure out if the issue is on my end now haha

**Comment by wojtekmaj** [comment] 2018-03-15 07:49
@nathan-haines, it has landed on master branch; now I just need info from Lisa if the other part of the fix had worked :) I'd rather push an entire fix.

For those interested - Internet Explorer seems to be ignoring `box-sizing: border-box` property when in flex boxes. Tiles are measured to have exactly `100% / 7` width, but Internet Explorer measures them and THEN applies the padding which makes the tiles larger. `max-width: 100% / 7` does the trick.

**Comment by brettshumaker** [comment] 2018-03-15 11:36
@wojtekmaj Adding `margin:0` to  `.react-calendar_tile` fixes the issue for me in safari (iOS and desktop)

**Closed** 2018-03-15 20:29 UTC
Labels: bug

**Comment by lisahoong** [comment] 2018-03-15 21:13
Thank you so much!!

**Comment by wojtekmaj** [comment] 2018-03-15 21:16
My pleasure :)
